name: "dysche-cli"
version: "0.1.0"
about: "Cli tools for dysche partition management"
author: "Guangxing Deng. <dengguangxing@huawei.com>, Liang Li <liliang6@me.com>"

args:
  - verbose:
      help: "show verbose help infos"
      short: v
      multiple: false

subcommands:
  - create:
      about: "create an app partition"
      short: c
      multiple: false
      args:
        - cpu:
            help: "core (lists) for the newly created partition"
            takes_value: true
            short: c
        - kernel:
            help: "the kernel image for the newly created partition"
            takes_value: true
            short: k
        - bootargs:
            help: "the kernel boot cmdline params for the newly created partition"
            takes_value: true
            short: b

  - destroy:
      about: "destroy an app partition"
      short: d
      multiple: false
      args:
        - pid:
            help: "specify partition id that will be destoried."
            takes_value: true
            short: p

  - migrate:
      about: "migrate an app partition"
      short: m
      multiple: true
      args:
        - cpu:
            help: "specify core(list) that will be migrated"
            takes_value: true
            short: c
        - source_partition:
            help: "specify the source partition that resource migrated out"
            takes_value: true
            short: s
        - dest_partition:
            help: "specify the dest partition that resource migrated in"
            takes_value: true
            short: d

  - list:
      about: "show available partitions"
      args:
        - verbose:
            help: "show partition info verbosely"
            short: v